inhibit_all_warnings!
platform :ios, '7.0'

target 'NewsApp' do

pod 'AFNetworking', '3.1.0'   
pod 'Masonry', '1.0.0'
pod 'FMDB', '2.6.2’
pod 'MJRefresh', '3.1.0’
pod 'MJExtension', '3.0.10'
pod 'SDWebImage', '3.7.5'
pod 'WebViewJavascriptBridge', '5.0.5'
pod 'GTMBase64', '1.0.0'
pod 'SSKeychain', '1.4.0'
pod 'NJKWebViewProgress', '0.2.3'
pod 'MBProgressHUD', '0.9.2'

end
